AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Role for GitHub Actions to perform administrator-level actions in AWS.

Resources:
  GitHubActionsAdminRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "GitHubActions-Admin-Role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: "sts.amazonaws.com"
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub "repo:karthikeyanbaluchamy/AWSCF:*"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: "https://token.actions.githubusercontent.com"
      ClientIdList:
        - "sts.amazonaws.com"
      ThumbprintList:
        - "6938fd4d98bab03faadb97b34396831e3780aea1"
