AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda Function Deployment

Parameters:
  LambdaS3Bucket:
    Type: String

  LambdaS3Key:
    Type: String

Resources:

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "LambdaExecutionRole-${AWS::StackName}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  TestLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: test-lambda
      Handler: index.handler
      Runtime: python3.12
      Code:
        S3Bucket: !Ref LambdaS3Bucket
        S3Key: !Ref LambdaS3Key
      Role: !GetAtt LambdaExecutionRole.Arn
