name: Delete CloudFormation Stack

on:
  workflow_dispatch:   # Manually triggered workflow

permissions:
  id-token: write      # Required for OIDC role assumption
  contents: read

jobs:
  delete-stack:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl zip unzip

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -o awscliv2.zip
          sudo ./aws/install --update
          aws --version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/GitHubActions-Admin-Role
          role-session-name: GitHubActions
          aws-region: ${{ vars.AWS_REGION }}

      - name: Delete CloudFormation stack
        run: |
          STACK_NAME="Deploy Test"
          echo "Deleting stack: $STACK_NAME"
          aws cloudformation delete-stack --stack-name "$STACK_NAME"

          echo "Waiting for stack deletion to complete..."
          aws cloudformation wait stack-delete-complete --stack-name "$STACK_NAME"
          echo "Stack deleted successfully."
